[experiment]
end_date = "2025-11-19"

[metrics]

# overwrite all irrelevant metrics with no-op

# overwrite all metrics in Networking outcome: https://github.com/mozilla/metric-hub/blob/main/jetstream/outcomes/firefox_desktop/networking.toml
[metrics.dns_lookup_time]
select_expression = 'SUM(0)'
data_source = "noop_source"


[metrics.http_page_tls_handshake]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_page_tls_handshake.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_page_tls_handshake.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_page_tls_handshake.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_sub_tls_handshake]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_sub_tls_handshake.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_sub_tls_handshake.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_sub_tls_handshake.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_page_open_to_first_sent]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_page_open_to_first_sent.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_page_open_to_first_sent.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_page_open_to_first_sent.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.time_to_response_start_ms]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.time_to_response_start_ms.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.time_to_response_start_ms.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.time_to_response_start_ms.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.cert_error_page_loaded]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.cert_error_page_loaded.statistics.bootstrap_mean]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.cert_error_page_loaded.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.cert_error_page_loaded.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.cert_error_page_loaded.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.cert_error_page_clicked]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.cert_error_page_clicked.statistics.bootstrap_mean]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.cert_error_page_clicked.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.cert_error_page_clicked.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.cert_error_page_clicked.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_transactions_using_tls]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_transactions_using_tls.statistics.bootstrap_mean]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_transactions_using_tls.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_transactions_using_tls.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_transactions_using_tls.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_pageloads_using_tls]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_pageloads_using_tls.statistics.bootstrap_mean]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_pageloads_using_tls.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_pageloads_using_tls.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_pageloads_using_tls.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_channels_success]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_channels_success.statistics.bootstrap_mean]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_channels_success.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_channels_success.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_channels_success.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_cert_validation_time]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_cert_validation_time.statistics.bootstrap_mean]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_cert_validation_time.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_cert_validation_time.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_cert_validation_time.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_failed_cert_validation_time]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_failed_cert_validation_time.statistics.bootstrap_mean]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_failed_cert_validation_time.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_failed_cert_validation_time.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"


[metrics.tls_failed_cert_validation_time.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_connections_overall]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_connections_overall.statistics.bootstrap_mean]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_connections_overall.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_connections_overall.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_connections_overall.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"


[metrics.tls_successful_connections_with_ech]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_connections_with_ech.statistics.bootstrap_mean]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_connections_with_ech.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_connections_with_ech.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_connections_with_ech.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_connections_with_ech_grease]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_connections_with_ech_grease.statistics.bootstrap_mean]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_connections_with_ech_grease.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_connections_with_ech_grease.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_connections_with_ech_grease.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_first_try_connections]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_first_try_connections.statistics.bootstrap_mean]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_first_try_connections.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_first_try_connections.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_first_try_connections.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_conservative_connections]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_conservative_connections.statistics.bootstrap_mean]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_conservative_connections.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_conservative_connections.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.tls_successful_conservative_connections.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.quic_successful_connections_no_ech]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.quic_successful_connections_no_ech.statistics.bootstrap_mean]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.quic_successful_connections_no_ech.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.quic_successful_connections_no_ech.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.quic_successful_connections_no_ech.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"


[metrics.quic_successful_connections_ech_grease]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.quic_successful_connections_ech_grease.statistics.bootstrap_mean]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.quic_successful_connections_ech_grease.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.quic_successful_connections_ech_grease.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.quic_successful_connections_ech_grease.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.quic_successful_connections_ech_real]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.quic_successful_connections_ech_real.statistics.bootstrap_mean]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.quic_successful_connections_ech_real.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.quic_successful_connections_ech_real.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.quic_successful_connections_ech_real.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"

# overwrite all metrics in Networking Performance outcome: https://github.com/mozilla/metric-hub/blob/main/jetstream/outcomes/firefox_desktop/networking_performance.toml


[metrics.dns_lookup_time]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.dns_lookup_time.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.dns_lookup_time.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.dns_lookup_time.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"


[metrics.http_page_tls_handshake]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_page_tls_handshake.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_page_tls_handshake.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_page_tls_handshake.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"


[metrics.http_sub_tls_handshake]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_sub_tls_handshake.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_sub_tls_handshake.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_sub_tls_handshake.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_page_open_to_first_sent]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_page_open_to_first_sent.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_page_open_to_first_sent.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.http_page_open_to_first_sent.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.time_to_response_start_ms]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.time_to_response_start_ms.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.time_to_response_start_ms.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.time_to_response_start_ms.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"

#overwrite Upload, Download Performance outcome: https://github.com/mozilla/metric-hub/blob/main/jetstream/outcomes/firefox_desktop/upload_download_performance.toml


[metrics.networking_download_throughput_http_1]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.networking_download_throughput_http_1.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.networking_download_throughput_http_1.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.networking_download_throughput_http_1.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"


[metrics.networking_download_throughput_http_2]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.networking_download_throughput_http_2.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.networking_download_throughput_http_2.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.networking_download_throughput_http_2.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"


[metrics.networking_download_throughput_http_3]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.networking_download_throughput_http_3.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.networking_download_throughput_http_3.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.networking_download_throughput_http_3.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"


[metrics.networking_upload_throughput_http_1]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.networking_upload_throughput_http_1.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.networking_upload_throughput_http_1.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.networking_upload_throughput_http_1.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.networking_upload_throughput_http_2]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.networking_upload_throughput_http_2.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.networking_upload_throughput_http_2.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.networking_upload_throughput_http_2.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"


[metrics.networking_upload_throughput_http_3]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.networking_upload_throughput_http_3.statistics.deciles]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.networking_upload_throughput_http_3.statistics.kernel_density_estimate]
select_expression = 'SUM(0)'
data_source = "noop_source"

[metrics.networking_upload_throughput_http_3.statistics.empirical_cdf]
select_expression = 'SUM(0)'
data_source = "noop_source"


[data_sources.noop_source]
from_expression = """(
    SELECT
        '1234' AS client_id,
        '12345' AS profile_group_id,
        DATE('2022-01-01') AS submission_date
)"""
experiments_column_type = "none"
friendly_name = "No-Op"
description = "No-op that creates the required columns"


