[metrics]

# Metrics to compute for each weekly analysis window.
weekly = ["backup_scheduler_enabled"]

# Metrics to compute for each 28 days long analysis window
28_day = ["backup_scheduler_enabled"]

# Metrics to compute only for the overall analysis window.
overall = ["backup_scheduler_enabled"]

[metrics.backup_scheduler_enabled]
data_source = 'clients_daily'
select_expression = 'CAST(COALESCE(LOGICAL_OR(browser_backup_scheduler_enabled), FALSE) AS INT)'
friendly_name = "backup scheduler enabled"
description = "Firefox Backup scheduler enabled"

[metrics.backup_scheduler_enabled.statistics.binomial]