[experiment]
start_date = '2025-01-08'
enrollment_period = 14

[metrics]
overall = ['addons_count', 'addon_install']
weekly = ['addons_count', 'addon_install']

[metrics.addons_count]
select_expression = """COALESCE(MAX((SELECT ARRAY_LENGTH(ARRAY_AGG(IF(NOT is_system, addon_id, NULL) IGNORE NULLS)) FROM UNNEST(active_addons))), 0)"""
data_source = 'clients_daily'
friendly_name = 'Count of self-installed active addons'
description = 'The number of self-installed active addons'

[metrics.addon_install]
select_expression = """CAST(COALESCE(LOGICAL_OR((SELECT ARRAY_LENGTH(ARRAY_AGG(IF(NOT is_system, addon_id, NULL) IGNORE NULLS)) FROM UNNEST(active_addons)) > 0), FALSE) AS INT)"""
data_source = 'clients_daily'
friendly_name = 'Has Addon installed'
description = 'If addon installed'

[metrics.addons_count.statistics.bootstrap_mean]
[metrics.addon_install.statistics.binomial]
