[experiment]
end_date = "2026-01-20"
reference_branch = "control"

[metrics]
overall = ['urlbar_topsite_clicks']

[metrics.urlbar_topsite_clicks]
friendly_name = "Urlbar topsite clicks"
select_expression = "SUM(IF(product_result_type = 'top_site', urlbar_clicks, 0))"
data_source = "urlbar_events_daily_engagement_by_product_result_type_v1"

[metrics.urlbar_topsite_clicks.statistics.bootstrap_mean]

# No-op metrics

[metrics.organic_content_clicks]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.newtab_searches]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.newtab_content_enabled]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.newtab_sponsored_content_stories_enabled]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.organic_content_impressions]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.sponsored_content_ctr]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.any_sponsored_tiles_dismissals]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }


[metrics.sponsored_tiles_dismissals_pos1_2]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.newtab_any_searches]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.newtab_gt4_searches]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.sponsored_content_clicks]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.sponsored_content_impressions]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.sponsored_tile_ctr]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[data_sources.noop_source]
from_expression = """(
    SELECT
        '12345' AS client_id,
        '12345' AS profile_group_id,
        DATE('2022-01-01') AS submission_date
)"""
experiments_column_type = "none"
friendly_name = "No-Op"
description = "No-op that creates the required columns"
