[experiment]
sample_size = 20

[metrics]

[experiment]
reference_branch = "control"

[metrics]

[metrics.urlbar_topsite_clicks]
select_expression = "SUM(IF(product_result_type = 'top_site', urlbar_clicks, 0))"
data_source = "urlbar_events_daily_engagement_by_product_result_type_v1"


[data_sources.urlbar_events_daily_engagement_by_product_result_type_v1]
from_expression = """(
    SELECT * FROM `mozdata.firefox_desktop.urlbar_events_daily_engagement_by_product_result_type`
)"""
analysis_units = ["profile_group_id", "client_id"]
friendly_name = "Urlbar Events Clients Daily"
description = "Urlbar Events Clients Daily"
submission_date_column = "submission_date"
experiments_column_type = "native"
