[experiment]
reference_branch = "control"

# overwrite nonessential metrics with no-op

[metrics]

overall = ['urlbar_topsite_clicks']

[metrics.organic_pocket_clicks]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.newtab_searches]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.newtab_pocket_enabled]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.newtab_sponsored_pocket_stories_enabled]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.organic_pocket_impressions]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.sponsored_pocket_ctr]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.any_sponsored_tiles_dismissals]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }


[metrics.sponsored_tiles_dismissals_pos1_2]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.newtab_any_searches]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.newtab_gt4_searches]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.sponsored_pocket_clicks]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.sponsored_pocket_impressions]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.sponsored_tile_ctr]
select_expression = 'SUM(0)'
data_source = "noop_source"
statistics = { bootstrap_mean = {} }

[metrics.urlbar_topsite_clicks]
select_expression = "SUM(IF(product_result_type = 'top_site', urlbar_clicks, 0))"
data_source = "urlbar_events_daily_engagement_by_product_result_type_v1"
[metrics.urlbar_topsite_clicks.statistics.bootstrap_mean]
friendly_name = "Urlbar topsite clicks"

[data_sources.noop_source]
from_expression = """(
    SELECT
        '1234' AS client_id,
        '12345' AS profile_group_id,
        DATE('2022-01-01') AS submission_date
)"""
experiments_column_type = "none"
friendly_name = "No-Op"
description = "No-op that creates the required columns"
