
[experiment]

#segment information:https://docs.telemetry.mozilla.org/concepts/segments.html
segments = ["new_or_resurrected_v3", "regular_users_v3", "new_unique_profiles"]


[metrics]
# Metrics to compute for each weekly analysis window.
weekly = ["notification_clicks","used_vertical_tab"]

# Metrics to compute for each 28 days long analysis window
28_day = ["notification_clicks","used_vertical_tab"]

# Metrics to compute only for the overall analysis window.
overall = ["notification_clicks","used_vertical_tab"]

[metrics.used_vertical_tab]
#averaging the count of maximum number of tabs with vertical tabs enabled per client_id, branch over an analysis window
#probe:https://probes.telemetry.mozilla.org/?search=max_concurrent_vertical_tab_count&view=detail&probeId=scalar%2Fbrowser.engagement.max_concurrent_vertical_tab_count
select_expression= "CAST(SUM(COALESCE(payload.processes.parent.scalars.browser_engagement_max_concurrent_vertical_tab_count ,0)) > 0 AS INT)"
data_source = "main"
friendly_name = "vertical tab engagement"
description = "1 if the vertical tab count >0 else 0"


# Number of enrolled clients.
[metrics.notification_clicks.statistics.count]
# Number of clicks.
[metrics.notification_clicks.statistics.sum]
# Click through rate.
[metrics.notification_clicks.statistics.binomial]
# Average max number of taps opened. 
[metrics.used_vertical_tab.statistics.binomial]
