[project]

platform = "firefox_desktop"
xaxis = "submission_date"
metrics = [
    "any_organic_pocket_clicks",
    "sponsored_pocket_clicks",
    "organic_pocket_impressions",
    "sponsored_pocket_impressions",
    "sponsored_pocket_ctr",
    "organic_pocket_ctr",
    "newtab_pocket_enabled",
    "newtab_sponsored_pocket_stories_enabled",
]
is_rollout=true
skip_default_metrics=true

[project.population]

data_source = "newtab_clients_daily"

[metrics.any_organic_pocket_clicks.statistics]
mean = {}

[metrics.sponsored_pocket_clicks.statistics]
mean = {}

[metrics.organic_pocket_impressions.statistics]
mean = {}

[metrics.sponsored_pocket_impressions.statistics]
mean = {}

[metrics.sponsored_pocket_ctr.statistics]
mean = {}

[metrics.organic_pocket_ctr.statistics]
mean = {}

[metrics.newtab_pocket_enabled.statistics]
mean = {}

[metrics.newtab_sponsored_pocket_stories_enabled.statistics]
mean = {}
