[project]

platform = "firefox_desktop"
xaxis = "submission_date"
metrics = [
    "organic_content_clicks",
    "sponsored_content_clicks",
    "organic_content_impressions",
    "sponsored_content_impressions",
    "newtab_content_enabled",
    "newtab_sponsored_content_stories_enabled",
]
is_rollout=true
skip_default_metrics=true

[project.population]

data_source = "newtab_clients_daily"
boolean_pref = "mozfun.map.get_key(experiments, 'fr-billboard-rollout').branch IS NOT NULL"
dimensions=['country']

[metrics.organic_content_impressions.statistics]
mean = {}

[metrics.sponsored_content_impressions.statistics]
mean = {}

[metrics.organic_content_clicks.statistics]
mean = {}
total_ratio = { denominator_metric = "organic_content_impressions" }

[metrics.sponsored_content_clicks.statistics]
mean = {}
total_ratio = { denominator_metric = "sponsored_content_impressions" }

[metrics.newtab_content_enabled.statistics]
mean = {}

[metrics.newtab_sponsored_content_stories_enabled.statistics]
mean = {}

[dimensions]
[dimensions.country_code]
data_source = "newtab_clients_daily"
select_expression = "country"
