name: "Build docs"

on:
  push:
    branches:
      - main
      - deploy-docs-fix-2

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Build docs
      run: |
        python3.10 -m venv venv/
        venv/bin/python -m pip install -r .script/requirements.txt
        venv/bin/python -m pip install lib/metric-config-parser
        venv/bin/python .script/generate_docs.py \
          --output_dir=generated_docs/
        cd generated_docs/
        PATH="../venv/bin:$PATH" mkdocs gh-deploy \
          -m "[ci skip] Deployed {sha} with MkDocs version: {version}"
