name: "Validate jetstream"

on:
  pull_request:
    branches:
      - main
    paths:
      - 'jetstream/**'
  push:
    branches:
      - main
    paths:
      - 'jetstream/**'

jobs:
  changed:
    uses: ./.github/workflows/changed-files.yml
    with:
      path_filter: |
        jetstream/**/*.toml
        jetstream/**/*.toml.example

  validate-jetstream:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/moz-fx-data-experiments/jetstream:latest
    needs: changed
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    if: needs.changed.outputs.any_changed == 'true'
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        ref: ${{ github.head_ref }}
    - name: Set safe directory
      # workaround because actions/checkout's `set-safe-directory` flag doesn't work in containers
      # this and `ref` above are needed because jetstream performs git operations
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v3
      id: auth
      with:
        workload_identity_provider: ${{ vars.GCPV2_GITHUB_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_DRYRUN_SERVICE_ACCOUNT_EMAIL }}
        token_format: id_token
        id_token_audience: https://us-central1-moz-fx-data-shared-prod.cloudfunctions.net/dryrun
        id_token_include_email: true
    - name: Export ID Token for Python
      env:
        GOOGLE_GHA_ID_TOKEN: ${{ steps.auth.outputs.id_token }}
      run: echo "GOOGLE_GHA_ID_TOKEN=$GOOGLE_GHA_ID_TOKEN" >> $GITHUB_ENV
    - name: Validate jetstream config files
      id: validate_jetstream
      shell: bash {0}
      env:
        ALL_CHANGED_FILES: ${{ needs.changed.outputs.all_changed_files }}
      run: |
        # set +e allows this step to continue past the jetstream command even with a nonzero exit code
        set +e
        echo "Run validation on changed files: "
        echo "jetstream validate_config --config_repos='.' --config_repos=jetstream/ $ALL_CHANGED_FILES"
        jetstream validate_config --config_repos='.' --config_repos=jetstream/ $ALL_CHANGED_FILES
        export VALIDATE_EXIT_CODE=$?
        echo "JETSTREAM_EXIT_CODE=$VALIDATE_EXIT_CODE" >> $GITHUB_ENV
        
        # now we want to exit with an explicit code
        set -e
        if [[ "$VALIDATE_EXIT_CODE" -gt 1 ]]; then
          exit 0;
        else
          exit "$VALIDATE_EXIT_CODE";
        fi
    - name: Validation Success Message
      uses: actions/github-script@v8
      if: ${{ github.event_name == 'pull_request' && success() }}
      # add a helpful message about where to find generated SQL and data processing estimates
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          console.log("testing");
          console.log(process.env.JETSTREAM_EXIT_CODE);
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: "✅ Jetstream Validation is complete. Check the CI logs for this step for **Query SQL** and **data processing estimates**."
          });

          console.log("testing2");

          /* add a helpful message to the PR about high data processing estimates */
          if (process.env.JETSTREAM_EXIT_CODE == "2") {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "⚠️ Experiment metrics query data processing estimate exceeded high threshold and may timeout during analysis.\n\nThis does not block merging, but experiment analysis may timeout and require config changes."
            });
          }
