name: "Validate jetstream"

on:
  pull_request:
    branches:
      - main
    paths:
      - 'jetstream/**'
  push:
    branches:
      - main
    paths:
      - 'jetstream/**'

jobs:
  changed:
    uses: ./.github/workflows/changed-files.yml
    with:
      path_filter: |
        jetstream/**.toml
        jetstream/**.toml.example

  validate-jetstream:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/moz-fx-data-experiments/jetstream:latest
    needs: changed
    permissions:
      contents: read
      id-token: write
    if: needs.changed.outputs.any_changed == 'true'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Set safe directory
      # workaround because actions/checkout's `set-safe-directory` flag doesn't work in containers
      # this and `ref` above are needed because jetstream performs git operations
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      id: auth
      with:
        workload_identity_provider: ${{ vars.GCPV2_GITHUB_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_JETSTREAM_SERVICE_ACCOUNT_EMAIL }}
        # token_format: id_token
        # id_token_audience: https://us-central1-moz-fx-data-experiments.cloudfunctions.net/bigquery-etl-dryrun
        # id_token_include_email: true
    - name: Validate jetstream config files
      run: |
        echo "Run validation on changed files: "
        echo ${{ needs.changed.outputs.all_changed_files }}
        echo "jetstream validate_config --config_repos='.' --config_repos=jetstream/ ${{ needs.changed.outputs.all_changed_files }}"
        jetstream validate_config --config_repos='.' --config_repos=jetstream/ ${{ needs.changed.outputs.all_changed_files }}



